{{- if or .Values.configSecret.create .Values.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dex.configSecretName" . }}
  labels:
    {{- include "dex.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.configSecret.create }}
  config.yaml: {{ .Values.config | toYaml | b64enc | quote }}
  {{- end }}
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
  {{- end }}
{{- end }}


