{{- if .Values.configSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dex.configSecretName" . }}
  labels:
    {{- include "dex.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
type: Opaque
data:
  config.yaml: {{ .Values.config | toYaml | b64enc | quote }}
{{- end }}
